name: Weekly Tests
run-name: Testing Weeklies on VM
#  allows us to repeat this daily at 4am
#  https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
on:
  schedule:
    - cron:  '0 * * 1 *'

# This is a WIP file for recreating weekly.sh
jobs:
  Weeklies:
    runs-on: [self-hosted, linux, x64, build]
    # running container with only a single arguement passes the image being used
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    timeout-minutes: 4320 # 3 days
    env:
    # currently hard coded
      GEM5ROOT_PATH: /runner/_work/gem5-actions/gem5-actions

    steps:
    # checks out repository, should be more useful when
    # running checks on changed files
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run very-long tests
        run: |
          nproc
          cd tests
          ./main.py run --length very-long -j $(nproc) -vv

          mkdir -p tests/testing-results

      # upload testing results
      - uses: actions/download-artifact@v3
        with:
          name: weekly-testing-results
          path: tests/testing-results
      - run: echo "üçè This job's status is ${{ job.status }}."

  GPU-Tests:
    runs-on: [self-hosted, linux, x64, run]
    # container: gcr.io/gem5-test/gcn-gpu:latest
    timeout-minutes: 4320 # 3 days
    env:
      # need to not hard code this
      GEM5ROOT_PATH: /runner/_work/gem5-actions/gem5-actions
      # The per-container Docker memory limit.
      docker_mem_limit: 24g
      gpu_isa: GCN3_X86

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: start gpu tests
        run: |
          rm -rf gem5-resources
          rm -f coAuthorsDBLP.graph 1k_128k.gr result.out

      - name: Check out gem5 resources
        run: |
          git clone https://gem5.googlesource.com/public/gem5-resources \
          "gem5-resources"
          cd gem5-resources
          git checkout develop
          cd ../

      - name: create docker images
        run: |
          docker pull gcr.io/gem5-test/gcn-gpu:latest
          docker build -t hacc-test-weekly gem5-resources/src/gpu/halo-finder  

      - name: start running tests
        run: |
          docker run --rm -u $UID:$GID --volume "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -w \
            "${GEM5ROOT_PATH}" --memory="${docker_mem_limit}" hacc-test-weekly bash -c \
            "scons build/${gpu_isa}/gem5.opt -j$(nproc) --ignore-style \
            || rm -rf build && scons build/${gpu_isa}/gem5.opt -j$(nproc) \
            --ignore-style"
          docker run --rm -u $UID:$GID --volume "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -w \
            ${GEM5ROOT_PATH}/util/m5 --memory="${docker_mem_limit}" hacc-test-weekly bash -c \
            "export TERM=xterm-256color ; scons build/x86/out/m5" 

      - name: lulesh tests
        run: | # build LULESH
          docker run --rm --volume "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -w \
            ${GEM5ROOT_PATH}/gem5-resources/src/gpu/lulesh \
            -u $UID:$GID --memory="${docker_mem_limit}" hacc-test-weekly bash -c \
            "make"
          docker run --rm -u $UID:$GID --volume "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -w \
            "${GEM5ROOT_PATH}" --memory="${docker_mem_limit}" \
            hacc-test-weekly build/${gpu_isa}/gem5.opt configs/example/apu_se.py -n3 \
            --mem-size=8GB --reg-alloc-policy=dynamic \
            --benchmark-root=${GEM5ROOT_PATH}/gem5-resources/src/gpu/lulesh/bin -c lulesh
      
      - name: test DNNMark
        run: | # setup cmake for DNNMark
          docker run --rm -u $UID:$GID --volume "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -w \
            "${GEM5ROOT_PATH}/gem5-resources/src/gpu/DNNMark" \
            --memory="${docker_mem_limit}" hacc-test-weekly bash -c "./setup.sh HIP"
          docker run --rm -u $UID:$GID --volume "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -w \
            "${GEM5ROOT_PATH}/gem5-resources/src/gpu/DNNMark/build" \
            --memory="${docker_mem_limit}" hacc-test-weekly bash -c \
            "make -j${threads}"
          docker run --rm --volume "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -w \
            "${GEM5ROOT_PATH}/gem5-resources/src/gpu/DNNMark" \
            "-v${GEM5ROOT_PATH}/gem5-resources/src/gpu/DNNMark/cachefiles:/root/.cache/miopen/2.9.0" \
            --memory="${docker_mem_limit}" hacc-test-weekly bash -c \
            "python3 generate_cachefiles.py cachefiles.csv --gfx-version=gfx801 \
            --num-cus=4"
          docker run --rm -u $UID:$GID --volume "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -w \
            "${GEM5ROOT_PATH}/gem5-resources/src/gpu/DNNMark" \
            --memory="${docker_mem_limit}" hacc-test-weekly bash -c \
            "g++ -std=c++0x generate_rand_data.cpp -o generate_rand_data"
          docker run --rm -u $UID:$GID --volume "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -w \
            "${GEM5ROOT_PATH}/gem5-resources/src/gpu/DNNMark" hacc-test-weekly bash -c \
            "./generate_rand_data"
          docker run --rm --volume "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -v \
            "${GEM5ROOT_PATH}/gem5-resources/src/gpu/DNNMark/cachefiles:/root/.cache/miopen/2.9.0" \
            -w "${GEM5ROOT_PATH}/gem5-resources/src/gpu/DNNMark" \
            --memory="${docker_mem_limit}" hacc-test-weekly \
            "${GEM5ROOT_PATH}/build/${gpu_isa}/gem5.opt" "${GEM5ROOT_PATH}/configs/example/apu_se.py" -n3 \
            --reg-alloc-policy=dynamic \
            --benchmark-root="${GEM5ROOT_PATH}/gem5-resources/src/gpu/DNNMark/build/benchmarks/test_fwd_softmax" \
            -c dnnmark_test_fwd_softmax \
            --options="-config ${GEM5ROOT_PATH}/gem5-resources/src/gpu/DNNMark/config_example/softmax_config.dnnmark \
            -mmap ${GEM5ROOT_PATH}/gem5-resources/src/gpu/DNNMark/mmap.bin"
          docker run --rm --volume "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -v \
            "${GEM5ROOT_PATH}/gem5-resources/src/gpu/DNNMark/cachefiles:/root/.cache/miopen/2.9.0" \
            -w "${GEM5ROOT_PATH}/gem5-resources/src/gpu/DNNMark" \
            --memory="${docker_mem_limit}" hacc-test-weekly \
            "${GEM5ROOT_PATH}/build/${gpu_isa}/gem5.opt" "${GEM5ROOT_PATH}/configs/example/apu_se.py" -n3 \
            --reg-alloc-policy=dynamic \
            --benchmark-root="${GEM5ROOT_PATH}/gem5-resources/src/gpu/DNNMark/build/benchmarks/test_fwd_pool" \
            -c dnnmark_test_fwd_pool \
            --options="-config ${GEM5ROOT_PATH}/gem5-resources/src/gpu/DNNMark/config_example/pool_config.dnnmark \
            -mmap ${GEM5ROOT_PATH}/gem5-resources/src/gpu/DNNMark/mmap.bin"
          docker run --rm --volume "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -v \
            "${GEM5ROOT_PATH}/gem5-resources/src/gpu/DNNMark/cachefiles:/root/.cache/miopen/2.9.0" \
            -w "${GEM5ROOT_PATH}/gem5-resources/src/gpu/DNNMark" \
            --memory="${docker_mem_limit}" hacc-test-weekly \
            "${GEM5ROOT_PATH}/build/${gpu_isa}/gem5.opt" "${GEM5ROOT_PATH}/configs/example/apu_se.py" -n3 \
            --reg-alloc-policy=dynamic \
            --benchmark-root="${GEM5ROOT_PATH}/gem5-resources/src/gpu/DNNMark/build/benchmarks/test_bwd_bn" \
            -c dnnmark_test_bwd_bn \
            --options="-config ${GEM5ROOT_PATH}/gem5-resources/src/gpu/DNNMark/config_example/bn_config.dnnmark \
            -mmap ${GEM5ROOT_PATH}/gem5-resources/src/gpu/DNNMark/mmap.bin"

      - name: test HACC
        run: | # build HACC
          docker run --rm -v ${PWD}:${PWD} -w \
            "${GEM5ROOT_PATH}/gem5-resources/src/gpu/halo-finder/src" -u $UID:$GID \
            --memory="${docker_mem_limit}" hacc-test-weekly make hip/ForceTreeTest
          docker run --rm -v "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -w "${GEM5ROOT_PATH}" -u $UID:$GID \
            --memory="${docker_mem_limit}" hacc-test-weekly \
            ${GEM5ROOT_PATH}/build/${gpu_isa}/gem5.opt \
            ${GEM5ROOT_PATH}/configs/example/apu_se.py -n3 --reg-alloc-policy=dynamic \
            --benchmark-root=${GEM5ROOT_PATH}/gem5-resources/src/gpu/halo-finder/src/hip \
            -c ForceTreeTest --options="0.5 0.1 64 0.1 1 N 12 rcb"

      - name: test Pannotia
        run: | # build HACC
          docker run --rm -v ${PWD}:${PWD} \
            -w ${GEM5ROOT_PATH}/gem5-resources/src/gpu/pannotia/bc -u $UID:$GID \
            --memory="${docker_mem_limit}" hacc-test-weekly bash -c \
            "export GEM5_PATH=${GEM5ROOT_PATH} ; make gem5-fusion"
          wget http://dist.gem5.org/dist/develop/datasets/pannotia/bc/1k_128k.gr
          docker run --rm -v "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -w "${GEM5ROOT_PATH}" -u $UID:$GID \
            --memory="${docker_mem_limit}" hacc-test-weekly \
            ${GEM5ROOT_PATH}/build/${gpu_isa}/gem5.opt \
            ${GEM5ROOT_PATH}/configs/example/apu_se.py -n3 --mem-size=8GB \
            --reg-alloc-policy=dynamic \
            --benchmark-root=gem5-resources/src/gpu/pannotia/bc/bin -c bc.gem5 \
            --options="1k_128k.gr"

      - name: build Color Max
        run: | 
          docker run --rm -v "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -w \
            ${GEM5ROOT_PATH}/gem5-resources/src/gpu/pannotia/color -u $UID:$GID \
            --memory="${docker_mem_limit}" hacc-test-weekly bash -c \
            "export GEM5_PATH=${GEM5ROOT_PATH} ; make gem5-fusion"
          docker run --rm -v ${GEM5ROOT_PATH}:${GEM5ROOT_PATH} -w ${GEM5ROOT_PATH} -u $UID:$GID \
            --memory="${docker_mem_limit}" hacc-test-weekly \
            ${GEM5ROOT_PATH}/build/${gpu_isa}/gem5.opt \
            ${GEM5ROOT_PATH}/configs/example/apu_se.py -n3 --mem-size=8GB \
            --reg-alloc-policy=dynamic \
            --benchmark-root=${GEM5ROOT_PATH}/gem5-resources/src/gpu/pannotia/color/bin \
            -c color_max.gem5 --options="1k_128k.gr 0"
          docker run --rm -v "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -w \
            ${GEM5ROOT_PATH}/gem5-resources/src/gpu/pannotia/color -u $UID:$GID \
            --memory="${docker_mem_limit}" hacc-test-weekly bash -c \
            "export GEM5_PATH=${GEM5ROOT_PATH} ; export VARIANT=MAXMIN ; make gem5-fusion"
          docker run --rm -v "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -w "${GEM5ROOT_PATH}" -u $UID:$GID \
            --memory="${docker_mem_limit}" hacc-test-weekly \
            ${GEM5ROOT_PATH}/build/${gpu_isa}/gem5.opt \
            ${GEM5ROOT_PATH}/configs/example/apu_se.py -n3 --mem-size=8GB \
            --reg-alloc-policy=dynamic \
            --benchmark-root=${GEM5ROOT_PATH}/gem5-resources/src/gpu/pannotia/color/bin \
            -c color_maxmin.gem5 --options="1k_128k.gr 0"

      - name: build FW
        run: | 
          docker run --rm -v "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -w \
            ${GEM5ROOT_PATH}/gem5-resources/src/gpu/pannotia/fw -u $UID:$GID \
            --memory="${docker_mem_limit}" hacc-test-weekly bash -c \
            "export GEM5_PATH=${GEM5ROOT_PATH} ; make gem5-fusion"
          docker run --rm -v "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -w "${GEM5ROOT_PATH}" -u $UID:$GID \
            --memory="${docker_mem_limit}" hacc-test-weekly \
            ${GEM5ROOT_PATH}/build/${gpu_isa}/gem5.opt \
            ${GEM5ROOT_PATH}/configs/example/apu_se.py -n3 --mem-size=8GB \
            --reg-alloc-policy=dynamic \
            --benchmark-root=${GEM5ROOT_PATH}/gem5-resources/src/gpu/pannotia/fw/bin \
            -c fw_hip.gem5 --options="1k_128k.gr"

      - name: build MIS
        run: | 
          docker run --rm -v "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -w \
            ${GEM5ROOT_PATH}/gem5-resources/src/gpu/pannotia/mis -u $UID:$GID \
            --memory="${docker_mem_limit}" hacc-test-weekly bash -c \
            "export GEM5_PATH=${GEM5ROOT_PATH} ; make gem5-fusion"
          docker run --rm -v "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -w "${GEM5ROOT_PATH}" -u $UID:$GID \
            --memory="${docker_mem_limit}" hacc-test-weekly \
            ${GEM5ROOT_PATH}/build/${gpu_isa}/gem5.opt \
            ${GEM5ROOT_PATH}/configs/example/apu_se.py -n3 --mem-size=8GB \
            --reg-alloc-policy=dynamic \
            --benchmark-root=${GEM5ROOT_PATH}/gem5-resources/src/gpu/pannotia/mis/bin \
            -c mis_hip.gem5 --options="1k_128k.gr 0"

      - name: build Pagerank Default variant
        run: | 
          docker run --rm -v "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -w \
            ${GEM5ROOT_PATH}/gem5-resources/src/gpu/pannotia/pagerank -u $UID:$GID \
            --memory="${docker_mem_limit}" hacc-test-weekly bash -c \
            "export GEM5_PATH=${GEM5ROOT_PATH} ; make gem5-fusion"
          wget http://dist.gem5.org/dist/develop/datasets/pannotia/pagerank/coAuthorsDBLP.graph
          docker run --rm -v "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -w "${GEM5ROOT_PATH}" -u $UID:$GID \
            --memory="${docker_mem_limit}" hacc-test-weekly \
            ${GEM5ROOT_PATH}/build/${gpu_isa}/gem5.opt \
            ${GEM5ROOT_PATH}/configs/example/apu_se.py -n3 --mem-size=8GB \
            --reg-alloc-policy=dynamic \
            --benchmark-root=${GEM5ROOT_PATH}/gem5-resources/src/gpu/pannotia/pagerank/bin \
            -c pagerank.gem5 --options="coAuthorsDBLP.graph 1"
          docker run --rm -v "${GEM5ROOT_PATH}:"${GEM5ROOT_PATH} -w \
            ${GEM5ROOT_PATH}/gem5-resources/src/gpu/pannotia/pagerank -u $UID:$GID \
            --memory="${docker_mem_limit}" hacc-test-weekly bash -c \
            "export GEM5_PATH=${GEM5ROOT_PATH} ; export VARIANT=SPMV ; make gem5-fusion"
          docker run --rm -v ${GEM5ROOT_PATH}:${GEM5ROOT_PATH} -w ${GEM5ROOT_PATH} -u $UID:$GID \
            --memory="${docker_mem_limit}" hacc-test-weekly \
            ${GEM5ROOT_PATH}/build/${gpu_isa}/gem5.opt \
            ${GEM5ROOT_PATH}/configs/example/apu_se.py -n3 --mem-size=8GB \
            --reg-alloc-policy=dynamic \
            --benchmark-root=${GEM5ROOT_PATH}/gem5-resources/src/gpu/pannotia/pagerank/bin \
            -c pagerank_spmv.gem5 --options="coAuthorsDBLP.graph 1"

      - name: build SSSP CSR variant
        run: | 
          docker run --rm -v ${GEM5ROOT_PATH}:${GEM5ROOT_PATH} -w \
            ${GEM5ROOT_PATH}/gem5-resources/src/gpu/pannotia/sssp -u $UID:$GID \
            --memory="${docker_mem_limit}" hacc-test-weekly bash -c \
            "export GEM5_PATH=${GEM5ROOT_PATH} ; make gem5-fusion"
          docker run --rm -v ${GEM5ROOT_PATH}:${GEM5ROOT_PATH} -w ${GEM5ROOT_PATH} -u $UID:$GID \
            --memory="${docker_mem_limit}" hacc-test-weekly \
            ${GEM5ROOT_PATH}/build/${gpu_isa}/gem5.opt \
            ${GEM5ROOT_PATH}/configs/example/apu_se.py -n3 --mem-size=8GB \
            --reg-alloc-policy=dynamic \
            --benchmark-root=${GEM5ROOT_PATH}/gem5-resources/src/gpu/pannotia/sssp/bin \
            -c sssp.gem5 --options="1k_128k.gr 0"
          docker run --rm -v ${GEM5ROOT_PATH}:${GEM5ROOT_PATH} -w \
            ${GEM5ROOT_PATH}/gem5-resources/src/gpu/pannotia/sssp -u $UID:$GID \
            --memory="${docker_mem_limit}" hacc-test-weekly bash -c \
            "export GEM5_PATH=${GEM5ROOT_PATH} ; export VARIANT=ELL ; make gem5-fusion"
          docker run --rm -v ${GEM5ROOT_PATH}:${GEM5ROOT_PATH} -w ${GEM5ROOT_PATH} -u $UID:$GID \
            --memory="${docker_mem_limit}" hacc-test-weekly \
            ${GEM5ROOT_PATH}/build/${gpu_isa}/gem5.opt \
            ${GEM5ROOT_PATH}/configs/example/apu_se.py -n3 --mem-size=8GB \
            --reg-alloc-policy=dynamic \
            --benchmark-root=${GEM5ROOT_PATH}/gem5-resources/src/gpu/pannotia/sssp/bin \
            -c sssp_ell.gem5 --options="1k_128k.gr 0"

      - name: Delete the gem5 resources repo we created
        run: | 
          docker run --rm --volume "${GEM5ROOT_PATH}":"${GEM5ROOT_PATH}" -w \
            "${GEM5ROOT_PATH}" --memory="${docker_mem_limit}" hacc-test-weekly bash -c \
            "rm -rf ${GEM5ROOT_PATH}/gem5-resources"
          rm -rf ${GEM5ROOT_PATH}/m5out
          rm -f coAuthorsDBLP.graph 1k_128k.gr result.out
